management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include:
        - health
        - info
  endpoint:
    health:
      show-details: always
spring:
  graphql:
    graphiql:
      enabled: true